### ISSUE TITLE
Wrong link in the Task list

### ISSUE THREAD

**Issue by manovik** [rolling-scopes-school/RS-Short-Track#1]
Here https://github.com/rolling-scopes-school/RS-Short-Track/wiki

**6th task should have link**
https://github.com/rolling-scopes-school/RS-Short-Track/wiki/6.-Cyclic-menu

**instead of**
https://github.com/rolling-scopes-school/RS-Short-Track/wiki/5.-Cyclic-menu

**Comment by Shastel** [comment]
fixed, thx
